# Load in Numpy to perform .

In [200]:
# list -  Python lists are flexible containers that can hold mixed types but are slower and less efficient for mathematical operations.

# Numpy - NumPy arrays are optimized for fast, memory-efficient numerical computations with homogeneous data,

In [201]:
import numpy as np

## The Basics

In [202]:
# 1-D 
a = np.array([1,2,3], dtype = 'int32')# change the data storage
print(a)
print(a.dtype)

[1 2 3]
int32


In [203]:
# 2 -dimension
b = np.array([[2.0, 3.0,4.0],[6.0,7.0,8.0]])
print(b)


[[2. 3. 4.]
 [6. 7. 8.]]


In [204]:
# Get the dimension
b.ndim 


2

In [205]:
# How many Rows and Columns (Rows,columns)
b.shape

(2, 3)

In [206]:
# Get the datatype
b.dtype
a.dtype

dtype('int32')

In [207]:
# Get Size 
# 1 byte = 8 bit
# bool take 1 byte
# int32 take 4 byte int64 take 8 
# float take 8 byte
# string based on length
b.itemsize

8

In [208]:
# Get total size 
# nbytes - returns the total number of bytes consumed by the entire NumPy array (not just one element).
b.nbytes

48

# Accessing / changing specific elements, rows, columns etc

In [209]:
a = np.array([
    [1,2,3,4,5,6,7],
    [8,9,10,11,12,13,14]
])

In [210]:
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [211]:
# Get a specific element [row, col]
# index start with 0
# a[1,-2] # negative indexing
a[1,5]# output 13


np.int64(13)

In [212]:
# Get a specific row
# Row 1 element
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [213]:
# Get a specific column
# column 2 elements
a[:,2]

array([ 3, 10])

In [214]:
# Getting a little more fancy [startindex:ending:stepsize]
# startindex = inlusive
# ending = Exclude
# step = jump
a[0,1:-1:2]

array([2, 4, 6])

In [215]:
# update value at given index
a[1,5] = 20
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

# 3- D Example

In [216]:
arr = [[[1,2],[3,4]],[[5,6],[7,8]]]

In [217]:
d = np.array(arr)
d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [218]:
arr = [[[1,2],[3,4]],[[5,6],[7,8]]]
arr

[[[1, 2], [3, 4]], [[5, 6], [7, 8]]]

In [219]:
dd = np.array(arr)
dd

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [220]:
dd.ndim

3

In [221]:
# Get specific element (work outside in)
# [depth, row, columns]
# depth if you make another matrix inside matrix 
dd[0,1,1]


np.int64(4)

In [222]:
# dd[depth_index, row_index]
dd[0,1]

array([3, 4])

In [223]:
# Replace


# Iniltializing Different Types of Arrays

In [224]:
# all zeros matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [225]:
# All 0s matrix 2D 3D
# (2, 3, 3) means:
#2 → There are 2 matrices (or "depth" layers).
#3 → Each matrix has 3 rows.
#3 → Each row has 3 columns.
np.zeros((2,3,3))
#np.zeros()

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [226]:
# all ones matrix
one = np.ones((2,3,4),dtype = 'int32')
print(one)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [227]:
one.dtype

dtype('int32')

In [228]:
# Any other number
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [229]:
# any other number(full_like)
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [230]:
# Random decimal number
# np.random.rand(3,4)
np.random.rand(2,3,4)

array([[[0.48041971, 0.26723474, 0.66671114, 0.64195678],
        [0.53194239, 0.78357692, 0.73583481, 0.63656904],
        [0.06275326, 0.34363174, 0.54662777, 0.2923797 ]],

       [[0.15011361, 0.27842375, 0.43005372, 0.124202  ],
        [0.44913156, 0.77491894, 0.24491778, 0.03188869],
        [0.10574156, 0.15965884, 0.70197913, 0.74762936]]])

In [231]:
#Random integer values
np.random.randit(7,size=(3,3))

AttributeError: module 'numpy.random' has no attribute 'randit'

In [235]:
# The identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [236]:
# Repeate an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis = 1)
print(r1)

[[1 1 1 2 2 2 3 3 3]]


In [237]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1]  = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## Be careful when copying arrays

In [238]:
a= np.array([1,2,3])
b =a #  arraay a in b
b[0] = 100 # 0 index is set to 100
print(a)

[100   2   3]


In [239]:
a= np.array([1,2,3])
b =a.copy() #  copy arraay 
b[0] = 100 # 0 index is set to 100
print(a)

[1 2 3]


## Mathematics

In [240]:
a = np.array ([1,2,3])
print(a)

[1 2 3]


In [241]:
# add 2 in all element of array
a+2

array([3, 4, 5])

In [242]:
# Substract
a-1

array([0, 1, 2])

In [243]:
a *2

array([2, 4, 6])

In [244]:
a**2 # exponent

array([1, 4, 9])

In [245]:
a/2

array([0.5, 1. , 1.5])

In [246]:
a//2 # floor division

array([0, 1, 1])

In [247]:
# Lets add another array 
a + b

array([101,   4,   6])

In [251]:
# Take the sin
np.sin(a)
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 ])

## Linear Algebra

In [254]:
a = np.ones((2,3))
print(a)
b = np.full((3,2),2)
print(b)


np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [258]:
# Find the deteminant
c = np.identity(3)
np.linalg.det(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# Determinant
# Trace 
# Singular Vector Decomposition
# Eingenvalues
# Matrix Norm
# Inverse

# Statistics

In [259]:
stats = np.array([[1,2,3],
                  [4,5,6]])
print(stats)

[[1 2 3]
 [4 5 6]]


In [263]:
# To get maximum values
max_va = np.max(stats)
print(max_va)

6


In [264]:
# to get minimum value we can use axis
min_val = np.min(stats)
print(min_val)

1


In [265]:
# TO get the mean or we can say the average value
avg_va = np.mean(stats)
print(avg_va)

3.5


In [267]:
# To add all values of array
add = np.sum(stats)
print(add)

21


# Reorganizing Arrays

In [269]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

# reshape((rows,columns))
# rshape it in rows
after = before.reshape((8,1))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [271]:
# Vertically Stacking Vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

# add vertically
np.vstack([v1,v2])


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [272]:
# Horizontal stack(rows,columns)
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

#add horizontaly
np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

# Miscellaneous

## Load Data from File

In [275]:
filedata = np.genfromtxt('data.txt', delimiter  = ',')
filedta = filedata.astype('int32')
print(filedata)

FileNotFoundError: data.txt not found.

## Booloean Masking And Advanced Indexing

In [ ]:
# Retuen true and false value
filedat > 50

In [276]:
# TO get data frame value
filedata[filedata > 50]

NameError: name 'filedata' is not defined

In [277]:
## You can index with a list in Numpy
a = np.array([1,2,3,4,5,6,7,8,9])
# access by index
a[[1,2,8]]

array([2, 3, 9])

In [ ]:
# find all 
np.all(filedata > 50, axis = 1)

In [ ]:
# use And operator

((filedata >50) & (filedata <100))

## Author- Ayush Kumar Maurya